name: Observation du code avec AI

on:  
  pull_request :
    types : [opened, synchronize]

permissions: write-all

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run code analysis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
        GITHUB_REF_NAME: ${{ secrets.GITHUB_REF_NAME }}
        API_KEY: ${{ secrets.API_KEY }}
      run: python analyze_commit.py
